/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-11-11 07:43:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.KhachHang;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.KhachHang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-md bg-dark navbar-dark\">\r\n");
      out.write("		<div class=\"container-fluid px-3\">\r\n");
      out.write("\r\n");
      out.write("			<!-- LOGO -->\r\n");
      out.write("			<a class=\"navbar-brand me-auto d-flex align-items-center\" href=\"#\"> <img\r\n");
      out.write("				src=\"images/banner1.jpg\" alt=\"Logo\" class=\"rounded-circle me-2\"\r\n");
      out.write("				style=\"width: 50px; height: auto;\"> <span class=\"navbar-text text-light fw-bold\">Logo</span>\r\n");
      out.write("			</a>\r\n");
      out.write("\r\n");
      out.write("			<!-- TOGGLER BUTTON FOR MOBILE VIEW -->\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("				data-bs-target=\"#navbarNav\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<!-- NAV LINKS SECTION -->\r\n");
      out.write("			<div class=\"collapse navbar-collapse justify-content-center me-auto\" id=\"navbarNav\">\r\n");
      out.write("				<!-- NAV LINKS -->\r\n");
      out.write("				<ul class=\"navbar-nav\">\r\n");
      out.write("					<li class=\"nav-item me-3\"><a class=\"nav-link text-light\" href=\"index.jsp\">Trang chủ</a></li>\r\n");
      out.write("					<li class=\"nav-item dropdown me-3\"><a class=\"nav-link dropdown-toggle text-light\" href=\"#\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\"> Danh Mục Sản Phẩm </a>\r\n");
      out.write("						<ul class=\"dropdown-menu shadow\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Another Link</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Third Link</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class=\"nav-item me-3\"><a class=\"nav-link text-light\" href=\"#\">About</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link text-light\" href=\"#\">Contact</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- LOGIN/REGISTER OR PROFILE SECTION -->\r\n");
      out.write("			<div class=\"d-flex ms-auto\">\r\n");
      out.write("				");

				Object obj = session.getAttribute("khachHang");
				KhachHang khachHang = (obj != null) ? (KhachHang) obj : null;

				if (khachHang == null) {
				
      out.write("\r\n");
      out.write("				<a href=\"login.jsp\" class=\"btn btn-outline-light me-2\">Đăng nhập</a> <a href=\"register.jsp\"\r\n");
      out.write("					class=\"btn btn-primary\">Đăng ký</a>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<div class=\"dropdown\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-outline-light dropdown-toggle\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("						");
      out.print(khachHang.getUsername());
      out.write("\r\n");
      out.write("					</button>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-end shadow\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"profile.jsp\">Thông tin cá nhân</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"changepassword.jsp\">Đổi mật khẩu</a></li>\r\n");
      out.write("						<li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"do-logout\">Thoát</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<div class=\"container banner mt-1\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<h1>DU LỊCH VIỆT NAM</h1>\r\n");
      out.write("				<p>Trải nghiệm khắp đất nước Việt Nam với Pystravel</p>\r\n");
      out.write("				<a href=\"https://pystravel.vn\">Khám phá</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<div class=\"container mt-5\">\r\n");
      out.write("			<h1>TOUR HOT TRONG THÁNG</h1>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3 p-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 p-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 p-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 p-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<div class=\"container mt-3\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- LEFT CONTENT -->\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<h1>TOUR TRONG NƯỚC</h1>\r\n");
      out.write("					<div class=\"row box-hot-tour\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<a href=\"#\">Tour Nha Trang</a>\r\n");
      out.write("							<p>Giá Tour: 2.300.000 VNĐ</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row box-hot-tour\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<a href=\"#\">Tour Nha Trang</a>\r\n");
      out.write("							<p>Giá Tour: 2.300.000 VNĐ</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row box-hot-tour\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<a href=\"#\">Tour Nha Trang</a>\r\n");
      out.write("							<p>Giá Tour: 2.300.000 VNĐ</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- RIGHT CONTENT -->\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<h1>TOUR NƯỚC NGOÀI</h1>\r\n");
      out.write("					<div class=\"row box-hot-tour\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<a href=\"#\">Tour Nha Trang</a>\r\n");
      out.write("							<p>Giá Tour: 2.300.000 VNĐ</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row box-hot-tour\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<a href=\"#\">Tour Nha Trang</a>\r\n");
      out.write("							<p>Giá Tour: 2.300.000 VNĐ</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row box-hot-tour\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<a href=\"#\">Tour Nha Trang</a>\r\n");
      out.write("							<p>Giá Tour: 2.300.000 VNĐ</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<div class=\"container mt-5\">\r\n");
      out.write("			<h1>Danh Mục Sản Phẩm</h1>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-4 box-category\">\r\n");
      out.write("					<a href=\"#\">Tour Team Building</a> <img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 box-category\">\r\n");
      out.write("					<a href=\"#\">Tour Team Building</a> <img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 box-category\">\r\n");
      out.write("					<a href=\"#\">Tour Team Building</a> <img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-3\">\r\n");
      out.write("				<div class=\"col-md-4 box-category\">\r\n");
      out.write("					<a href=\"#\">Tour Team Building</a> <img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 box-category\">\r\n");
      out.write("					<a href=\"#\">Tour Team Building</a> <img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 box-category\">\r\n");
      out.write("					<a href=\"#\">Tour Team Building</a> <img alt=\"\" src=\"images/banner1.jpg\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
